### ISSUE TITLE
Crash with Qt6

### ISSUE THREAD

**Issue by blackPantherOS** [ashmanix/obs-plugin-countdown#46]
Hello,
Crashing when I try add Countdown dock to main window

```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
QDockWidgetLayout::minimumSize (this=0x257d1d0) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/widgets/qdockwidget.cpp:413
413         return sizeFromContent(content, w->isFloating());
```

<details>
<summary>Click to toggle long output of `GDB backtrace`</summary>

```
(gdb) backtrace
#0  QDockWidgetLayout::minimumSize() const (this=0x257d1d0) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/widgets/qdockwidget.cpp:413
#1  0x00007ffff57ee315 in QLayout::totalMinimumSize() const (this=this@entry=0x257d1d0) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qlayout.cpp:633
#2  0x00007ffff57ef6ba in QLayout::activate() (this=<optimized out>) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qlayout.cpp:1028
#3  0x00007ffff5811332 in QWidgetPrivate::setVisible(bool) (this=0x24a8810, visible=<optimized out>)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qwidget.cpp:8345
#4  0x0000000000505d16 in QtPrivate::QFunctorSlotObject<assignDockToggle(QDockWidget*, QAction*)::{lambda(bool)#2}, 1, QtPrivate::List<bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#5  0x00007ffff45bde05 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffbb30, r=0x2545510, this=<optimized out>)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qobjectdefs_impl.h:363
#6  doActivate<false>(QObject*, int, void**) (sender=0x2545510, signal_index=10, argv=0x7fffffffbb30)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qobject.cpp:3992
#7  0x00007ffff45b65ff in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=sender@entry=0x2545510, m=m@entry=0x7ffff52b7ea0, local_signal_index=local_signal_index@entry=7, argv=argv@entry=0x7fffffffbb30)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qobject.cpp:4052
#8  0x00007ffff4fc0b12 in QAction::toggled(bool) (this=this@entry=0x2545510, _t1=<optimized out>, _t1@entry=true)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/build/src/gui/Gui_autogen/include/moc_qaction.cpp:651
#9  0x00007ffff4fc370b in QAction::setChecked(bool) (this=0x2545510, b=<optimized out>) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/gui/kernel/qaction.cpp:891
#10 0x00007ffff4fc3815 in QAction::activate(QAction::ActionEvent) (this=0x2545510, event=<optimized out>)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/gui/kernel/qaction.cpp:1101
#11 0x00007ffff597ab95 in QMenuPrivate::activateCausedStack(QList<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool)
    (this=0xc60130, causedStack=..., action=0x2545510, action_e=QAction::Trigger, self=<optimized out>)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/widgets/qmenu.cpp:1398
#12 0x00007ffff5982593 in QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool)
    (this=0xc60130, action=0x2545510, action_e=QAction::Trigger, self=<optimized out>) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/widgets/qmenu.cpp:1480
#13 0x00007ffff5811828 in QWidget::event(QEvent*) (this=0xc60a70, event=0x7fffffffc1f0) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qwidget.cpp:9317
#14 0x00007ffff57bd3e2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x81bbd0, receiver=receiver@entry=0xc60a70, e=e@entry=0x7fffffffc1f0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qapplication.cpp:3287
#15 0x00007ffff57c6678 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=0xc60a70, e=0x7fffffffc1f0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qapplication.cpp:2774
#16 0x00007ffff455ff5a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0xc60a70, event=0x7fffffffc1f0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qcoreapplication.cpp:1118
#17 0x00007ffff57c51dd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool)
    (receiver=0xc60a70, event=event@entry=
    0x7fffffffc1f0, alienWidget=0x0, nativeWidget=0xc60a70, buttonDown=buttonDown@entry=0x7ffff5d8e490 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qapplication.cpp:2358
#18 0x00007ffff5823b0b in QWidgetWindow::handleMouseEvent(QMouseEvent*) (this=0x2924f00, event=0x7fffffffc4b0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qwidgetwindow.cpp:519
#19 0x00007ffff5825c58 in QWidgetWindow::event(QEvent*) (this=0x2924f00, event=0x7fffffffc4b0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qwidgetwindow.cpp:241
#20 0x00007ffff57bd3e2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x2924f00, e=0x7fffffffc4b0)
    at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/widgets/kernel/qapplication.cpp:3287
--Type <RET> for more, q to quit, c to continue without paging--c
#21 0x00007ffff455ff5a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x2924f00, event=0x7fffffffc4b0) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qcoreapplication.cpp:1118
#22 0x00007ffff4bf6a00 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=0x292af90) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/gui/kernel/qguiapplication.cpp:2299
#23 0x00007ffff4c4996c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=flags@entry=...) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/gui/kernel/qwindowsysteminterface.cpp:1094
#24 0x00007fffdef4aa3a in xcbSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:57
#25 0x00007ffff15df5e8 in g_main_dispatch (context=0x7fffd8005010) at ../glib/gmain.c:3454
#26 g_main_context_dispatch (context=0x7fffd8005010) at ../glib/gmain.c:4172
#27 0x00007ffff15df938 in g_main_context_iterate (context=context@entry=0x7fffd8005010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4248
#28 0x00007ffff15df9df in g_main_context_iteration (context=0x7fffd8005010, may_block=1) at ../glib/gmain.c:4313
#29 0x00007ffff47ce44a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x8d38f0, flags=...) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#30 0x00007ffff456b8bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffc830, flags=..., flags@entry=...) at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/global/qflags.h:34
#31 0x00007ffff4567d5e in QCoreApplication::exec() () at /usr/src/debug/qtbase6-6.5.2-1bP.x86_64/src/corelib/global/qflags.h:74
#32 0x0000000000463599 in main ()
(gdb) quit
A debugging session is active.

</details>

**Comment by ashmanix** [comment]
Hi, do you still have this issue?

**Comment by ashmanix** [comment]
I have updated the code to use a later version of OBS to build from and don't have any issues running any of the build and packaging scripts for Ubuntu, Windows and MacOS currently. Can you try pulling down the latest version of the code and seeing if the issue goes away?

Closing this for now but if there are still issues please reopen the issue.
